baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Водата'
theme = 'mytheme'
relativeURLS = true

[module]
    [[module.mounts]]
      source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
      target = "assets/js/bootstrap.bundle.min.js"